name: sorel
channels:
  - defaults
  - pytorch
dependencies:
  - pip
  - python=3.8
  - pytorch::pytorch==1.12.1
  - pytorch::torchvision==0.13.1
  - numpy==1.23.0
  - tqdm
  - scikit-learn
  - lightgbm
  - matplotlib
  - pandas
  - pip:
    - baker==1.3
    - lmdb==1.7.3
    - logzero==1.5.0
    - msgpack==0.6.2
    - lief==0.10.1
    - git+https://github.com/elastic/ember.git@d97a0b523de02f3fe5ea6089d080abacab6ee931
    - msgpack-numpy==0.4.8
    - git+https://github.com/pefe-system/pefe-agent.git@ebfcff95ec626242cc97b6e7b313a2ebbdd508cd#egg=pefe_agent
    - git+https://github.com/pefe-system/pefe-ief.git@71be9df0ed8703d2ad1f2ce30ea2c913a7601f57#egg=pefe_ief
