name: sorel
channels:
  - defaults
  - pytorch
dependencies:
  - pip
  - python=3.10
  - pytorch::pytorch==1.12.1
  - pytorch::torchvision==0.13.1
  - cudatoolkit=11.8
  - numpy<2.0.0
  - tqdm
  - scikit-learn
  - lightgbm
  - matplotlib
  - pandas
  - pip:
    - baker==1.3
    - lmdb==1.7.3
    - logzero==1.5.0
    - msgpack==0.6.2
    - git+https://github.com/elastic/ember.git@d97a0b523de02f3fe5ea6089d080abacab6ee931
