from ..models.abstract_model import AbstractModel
from typing import Type
import lmdb
from pefe_agent.config import *
import msgpack
import msgpack_numpy
import numpy as np
from tqdm import trange
import gc
import os
from pathlib import Path
import re
from .evaluation import evaluate

msgpack_numpy.patch()

def SORT_KEY(filename: str):
    # so that we get epoch_2 before epoch_10, not the other way around
    maTch = re.search(r'(\d+)', filename)
    num = -1
    if maTch:
        num = int(maTch.group(1))
    return (num, filename)

def clean_filename(filename):
    # Generated by Gemini
    # Define a pattern for common illegal characters in Windows and Linux
    # This pattern excludes alphanumeric characters, underscores, hyphens, and periods
    illegal_chars_pattern = r'[<>:"/\\|?*\x00-\x1F]'
    cleaned_filename = re.sub(illegal_chars_pattern, '_', filename)
    return cleaned_filename

def ief_all(models_dirs_and_classes, threshold, results_dir):
    # type: (dict[str, Type[AbstractModel]], float, str) -> None

    # Sanity check
    for models_dir_path, model_class in models_dirs_and_classes.items():
        if not os.path.isdir(models_dir_path):
            print(f"ERROR: While inspecting models of type {model_class.__name__}:")
            print(f"Directory does not exist: {models_dir_path} ")
            return
    if not os.path.isdir(results_dir):
        print(f"ERROR: Results directory does not exist: {results_dir}")
        return
    IMAGES_DIR_PATH = Path(results_dir) / "images"
    os.makedirs(IMAGES_DIR_PATH, exist_ok=True)
    INDEX_FILE_PATH = Path(results_dir) / "index.msgpack"
    index_file = open(INDEX_FILE_PATH, 'wb')

    try:
        print(f"Step 1/2: Loading data...", flush=True)
        db = lmdb.open(config['self']['lmdb_path'], readonly=True, lock=False, map_size=1024 * 1024 * 1024 * 1024) # 1 TB
        y_test = []
        X_test = []
        num_entries = 0
        with db.begin() as txn:
            stat_info = txn.stat()
            num_entries = stat_info['entries']

            cursor = txn.cursor()
            PROGRESS = trange(num_entries)
            for k, v in cursor:
                PROGRESS.update()
                payload = msgpack.unpackb(v, raw=False)

                label = payload['lb']       # int
                y_test.append(label)

                features = payload['ef']    # numpy array
                X_test.append(features)

        assert PROGRESS.n == num_entries
        PROGRESS.close()

        print(f"Step 1/2: Loading data: Realigning...", flush=True)
        gc.collect()
        X_test = np.array(X_test)
        gc.collect()
        y_test = np.array(y_test)
        gc.collect()

        print(f"Step 2/2: Running and evaluating models...", flush=True)
        RESULTS = []
        def ief_on_model_file(model_class, checkpoint_path):
            # type: (Type[AbstractModel], str) -> None
            if not (checkpoint_path.endswith(".pt") or checkpoint_path.endswith(".model")):
                print(f"NOTE: Skipping file as it does not appear to be a model/checkpoint file: {checkpoint_path}")
            else:
                nonlocal X_test, y_test
                nonlocal results_dir
                nonlocal RESULTS

                MODEL_TYPE = model_class.__name__
                MODEL_PATH = os.path.abspath(checkpoint_path)

                print("=======================================================================")
                print(f"Evaluating model: {MODEL_TYPE}", flush=True)
                print(f"checkpoint: {MODEL_PATH}", flush=True)
                print("=======================================================================")
                model = model_class()
                model.load(MODEL_PATH)
                y_probs = model.predict(X_test)
                del model
                gc.collect()

                figure_image_file_prefix = str(
                    IMAGES_DIR_PATH / (
                        clean_filename(f"{MODEL_TYPE}---{checkpoint_path}")
                    )
                )

                result = evaluate(
                    figure_image_file_prefix,
                    y_test, y_probs,
                    threshold
                )

                result.update({
                    "MODEL": {
                        "type": MODEL_TYPE,
                        "path": MODEL_PATH,
                    }
                })
                
                RESULTS.append(result)

        for models_dir_path, model_class in models_dirs_and_classes.items():
            for current_dir, dirnames, filenames in os.walk(models_dir_path, followlinks=True):
                dirnames.sort(key=SORT_KEY)
                filenames.sort(key=SORT_KEY)
                for filename in filenames:
                    filepath = os.path.join(current_dir, filename)
                    ief_on_model_file(model_class, filepath)
        
        msgpack.pack(RESULTS, index_file, use_bin_type=True)
        print()
        print(f"+++++++++++++++++++++++++++++++++++")
        print(f"Done. Numerical results and metadata have been saved to:")
        print(f"    {str(INDEX_FILE_PATH)}")
        print(f"+++++++++++++++++++++++++++++++++++")
    finally:
        index_file.close()
